server.port=8080
spring.application.name=gateway-service
spring.cloud.discovery.enabled=true
eureka.client.serviceUrl.defaultZone= http://localhost:8762/eureka

spring:
  cloud:
    discovery:
      enabled:
        t